"""
Extract per-document expert-coverage embeddings from an MoE model on the
weborganizer (cc_all_dressed) topic mix.

Standalone pipeline (does NOT plug into extract.py + transform.py): docs are
sampled uniformly across 24 cc_all_dressed topics on S3, run through the model
in one pass, and aggregated into per-document expert vectors. No per-token
data is persisted.

For each document and each layer, two embeddings are computed in a single
forward pass:

  1. doc_topk_freq -- normalized top-k selection frequency. For each layer,
     for each token, the routed_top_k experts (over standard experts only)
     are credited with +1; counts are divided by doc length so each layer
     slice sums to routed_top_k. Mirrors the per-doc statistic used by
     analyze_expert_coverage.py.

  2. doc_probs -- mean softmax probability per expert. Per token, softmax is
     taken over standard-expert logits only (shared experts excluded); the
     resulting distributions are averaged across the doc's tokens. Each
     layer slice sums to 1.0.

Usage
-----
    python -u -m src.scripts.clustering.extract_document \\
        --model-path models/.../step250339-hf \\
        --output-dir claude_outputs/clustering/weborganizer/<model_name>/ \\
        --composition-file claude_outputs/clustering/weborganizer/mix_composition.json \\
        --target-tokens 20000000 --batch-size 32

If --composition-file does not exist, it is generated by discovering topics
on S3 (uniform fractions across all available cc_all_dressed topics).
"""

import argparse
import gzip
import json
import logging
import os
import time
from typing import Any, Dict, List

import numpy as np
import torch

from src.scripts.clustering.utils import (
    ALL_DRESSED_PREFIX,
    BYTES_PER_TOKEN,
    EOS_TOKEN_ID,
    get_moe_config,
    list_npy_files,
    load_model_and_tokenizer,
    load_source_documents_shuffled,
    s3_ls,
)

logging.basicConfig(format="%(asctime)s [%(levelname)s] %(message)s", level=logging.INFO)
logger = logging.getLogger(__name__)


# ── Composition helpers ──────────────────────────────────────────────────────


def generate_uniform_composition(out_path: str) -> Dict[str, Any]:
    """Discover cc_all_dressed topics on S3 and write a uniform mix_composition.json."""
    logger.info("Discovering topics on S3 ...")
    topics = sorted(s3_ls(ALL_DRESSED_PREFIX))
    logger.info(f"Found {len(topics)} topics: {topics}")

    topic_files: Dict[str, list] = {}
    topic_vigintile: Dict[str, str] = {}

    for topic in topics:
        vigs = sorted(
            e for e in s3_ls(f"{ALL_DRESSED_PREFIX}/{topic}") if e.startswith("vigintile_")
        )
        if not vigs:
            logger.warning(f"  [{topic}] no vigintiles, skipping")
            continue
        max_vig = vigs[-1]
        topic_vigintile[topic] = max_vig

        files = list_npy_files(topic, max_vig)
        if not files:
            logger.warning(f"  [{topic}] no .npy files in {max_vig}, skipping")
            continue
        topic_files[topic] = files
        total_bytes = sum(sz for _, sz in files)
        logger.info(
            f"  [{topic}] {max_vig}: {len(files)} files, ~{total_bytes // BYTES_PER_TOKEN:,} tokens"
        )

    valid_topics = sorted(topic_files.keys())
    num_topics = len(valid_topics)
    uniform_fraction = 1.0 / num_topics

    composition = {
        "description": (
            "cc_all_dressed uniform mixing across topics "
            "(for doc-level expert coverage extraction)"
        ),
        "num_topics": num_topics,
        "sources": {
            topic: {
                "vigintile": topic_vigintile[topic],
                "num_files": len(topic_files[topic]),
                "est_tokens": sum(sz for _, sz in topic_files[topic]) // BYTES_PER_TOKEN,
                "total_bytes": sum(sz for _, sz in topic_files[topic]),
                "fraction": round(uniform_fraction, 6),
                "all_files": [path for path, _ in topic_files[topic]],
            }
            for topic in valid_topics
        },
    }

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as f:
        json.dump(composition, f, indent=2)
    logger.info(f"Saved mix_composition.json -> {out_path}")
    return composition


# ── Inference ────────────────────────────────────────────────────────────────


@torch.no_grad()
def process_batch(
    model: Any,
    batch_docs: List[np.ndarray],
    device: str,
    num_layers: int,
    num_standard_experts: int,
    routed_top_k: int,
) -> tuple:
    """
    Run a batch through the model. For each doc, compute:
      - topk_freq: per-layer normalized top-k selection frequency
                   (each layer sums to routed_top_k)
      - mean_probs: per-layer mean softmax over standard experts
                    (each layer sums to 1.0)

    Returns (B, num_layers * num_standard_experts) float32 arrays for both.
    """
    B = len(batch_docs)
    max_len = max(len(d) for d in batch_docs)

    input_ids = torch.full((B, max_len), EOS_TOKEN_ID, dtype=torch.long, device=device)
    attention_mask = torch.zeros((B, max_len), dtype=torch.long, device=device)
    for i, doc in enumerate(batch_docs):
        L = len(doc)
        input_ids[i, :L] = torch.from_numpy(doc.astype(np.int64)).to(device)
        attention_mask[i, :L] = 1

    outputs = model(
        input_ids=input_ids,
        attention_mask=attention_mask,
        output_router_logits=True,
    )

    counts = torch.zeros(B, num_layers, num_standard_experts, dtype=torch.float32, device=device)
    prob_sums = torch.zeros(
        B, num_layers, num_standard_experts, dtype=torch.float32, device=device
    )

    valid_mask = attention_mask.to(torch.float32)  # (B, S)

    for layer_idx, layer_logits in enumerate(outputs.router_logits):
        logits = layer_logits.view(B, max_len, -1)[:, :, :num_standard_experts].float()

        # Top-k frequency
        top_indices = logits.topk(routed_top_k, dim=-1).indices  # (B, S, k)
        flat_indices = top_indices.reshape(B, -1)  # (B, S*k)
        valid_repeated = (
            attention_mask.unsqueeze(-1).expand(-1, -1, routed_top_k).reshape(B, -1).to(torch.float32)
        )
        counts[:, layer_idx, :].scatter_add_(1, flat_indices, valid_repeated)

        # Mean softmax probs (standard experts only; shared experts excluded
        # before softmax, matching analyze_expert_coverage's slicing convention)
        probs = torch.softmax(logits, dim=-1)  # (B, S, num_standard_experts)
        masked_probs = probs * valid_mask.unsqueeze(-1)  # zero out padding
        prob_sums[:, layer_idx, :] = masked_probs.sum(dim=1)

    doc_lens = attention_mask.sum(dim=1, keepdim=True).float().clamp(min=1.0)  # (B, 1)
    doc_lens_3d = doc_lens.unsqueeze(-1)  # (B, 1, 1)

    topk_freq = counts / doc_lens_3d  # each layer sums to routed_top_k
    mean_probs = prob_sums / doc_lens_3d  # each layer sums to ~1.0

    topk_freq_flat = topk_freq.view(B, -1).cpu().numpy().astype(np.float32)
    mean_probs_flat = mean_probs.view(B, -1).cpu().numpy().astype(np.float32)

    torch.cuda.empty_cache()
    return topk_freq_flat, mean_probs_flat


# ── Main ─────────────────────────────────────────────────────────────────────


def main():
    parser = argparse.ArgumentParser(
        description="Extract per-doc expert-coverage embeddings on weborganizer topics"
    )
    parser.add_argument("--model-path", required=True, help="Path to HF MoE model checkpoint")
    parser.add_argument(
        "--output-dir",
        required=True,
        help="Output directory for embeddings + metadata",
    )
    parser.add_argument(
        "--composition-file",
        default=None,
        help=(
            "Path to mix_composition.json. If absent, will be generated at this path "
            "by discovering topics on S3 (uniform fractions). Defaults to "
            "claude_outputs/clustering/weborganizer/mix_composition.json."
        ),
    )
    parser.add_argument("--target-tokens", type=int, default=20_000_000)
    parser.add_argument("--batch-size", type=int, default=32)
    parser.add_argument("--min-doc-len", type=int, default=32)
    parser.add_argument("--max-doc-len", type=int, default=2048)
    parser.add_argument("--shuffle-seed", type=int, default=42)
    parser.add_argument(
        "--debug",
        action="store_true",
        help="Use only the first 2 topics for fast iteration",
    )
    args = parser.parse_args()

    if args.composition_file is None:
        args.composition_file = "claude_outputs/clustering/weborganizer/mix_composition.json"

    os.makedirs(args.output_dir, exist_ok=True)

    # ── Step 1: composition ──────────────────────────────────────────────────
    if os.path.exists(args.composition_file):
        logger.info(f"Loading composition from {args.composition_file}")
        with open(args.composition_file) as f:
            composition = json.load(f)
    else:
        logger.info(f"No composition at {args.composition_file}; generating ...")
        composition = generate_uniform_composition(args.composition_file)

    sources = composition["sources"]
    if args.debug:
        kept = dict(list(sorted(sources.items()))[:2])
        logger.info(f"DEBUG mode: using 2/{len(sources)} topics: {list(kept.keys())}")
        sources = kept
    num_topics = len(sources)
    tokens_per_topic = args.target_tokens // num_topics
    logger.info(
        f"{num_topics} topics, {tokens_per_topic:,} tokens/topic "
        f"({args.target_tokens:,} total)"
    )

    # ── Step 2: load docs (shuffled per topic) ───────────────────────────────
    logger.info("\nLoading documents from S3 (shuffled, seed=%d) ..." % args.shuffle_seed)
    all_docs: List[np.ndarray] = []
    all_labels: List[str] = []

    for topic, info in sorted(sources.items()):
        logger.info(f"  [{topic}] target ~{tokens_per_topic:,} tokens")
        docs = load_source_documents_shuffled(
            info["all_files"],
            tokens_per_topic,
            min_doc_len=args.min_doc_len,
            max_doc_len=args.max_doc_len,
            seed=args.shuffle_seed,
        )
        actual_tokens = sum(len(d) for d in docs)
        logger.info(f"  [{topic}] got {len(docs)} docs, {actual_tokens:,} tokens")
        all_docs.extend(docs)
        all_labels.extend([topic] * len(docs))

    total_tokens = sum(len(d) for d in all_docs)
    logger.info(
        f"\nTotal: {len(all_docs)} docs, {total_tokens:,} tokens across {num_topics} topics"
    )

    # ── Step 3: load model ───────────────────────────────────────────────────
    model, tokenizer = load_model_and_tokenizer(args.model_path)
    if hasattr(model, "hf_device_map"):
        first_device = next(iter(model.hf_device_map.values()))
        device = f"cuda:{first_device}" if isinstance(first_device, int) else str(first_device)
        logger.info(f"Multi-device model: {model.hf_device_map}")
    else:
        device = str(next(model.parameters()).device)
    logger.info(f"Input device: {device}")

    moe_cfg = get_moe_config(model)
    num_layers = moe_cfg["num_layers"]
    num_standard_experts = moe_cfg["num_standard_experts"]
    routed_top_k = moe_cfg["routed_top_k"]

    # ── Step 4: forward pass ─────────────────────────────────────────────────
    num_docs = len(all_docs)
    num_batches = (num_docs + args.batch_size - 1) // args.batch_size
    emb_dim = num_layers * num_standard_experts

    topk_freq_arr = np.zeros((num_docs, emb_dim), dtype=np.float32)
    mean_probs_arr = np.zeros((num_docs, emb_dim), dtype=np.float32)

    logger.info(
        f"\nProcessing {num_docs} docs in {num_batches} batches "
        f"(top_k={moe_cfg['top_k']}, routed={routed_top_k}, "
        f"shared={moe_cfg['num_shared_experts']})"
    )
    t0 = time.time()
    for batch_idx in range(num_batches):
        bs = batch_idx * args.batch_size
        be = min(bs + args.batch_size, num_docs)
        batch = all_docs[bs:be]

        tk, mp = process_batch(
            model, batch, device, num_layers, num_standard_experts, routed_top_k
        )
        topk_freq_arr[bs:be] = tk
        mean_probs_arr[bs:be] = mp

        if (batch_idx + 1) % 10 == 0 or batch_idx == num_batches - 1:
            elapsed = time.time() - t0
            rate = (batch_idx + 1) / elapsed if elapsed > 0 else 0
            eta = (num_batches - batch_idx - 1) / rate if rate > 0 else 0
            logger.info(
                f"  Batch {batch_idx+1}/{num_batches} ({(batch_idx+1)/num_batches:.0%})  "
                f"elapsed={elapsed/60:.1f}m  eta={eta/60:.1f}m"
            )

    # ── Step 5: validate ─────────────────────────────────────────────────────
    logger.info("\nValidating embeddings ...")
    tk_3d = topk_freq_arr.reshape(num_docs, num_layers, num_standard_experts)
    mp_3d = mean_probs_arr.reshape(num_docs, num_layers, num_standard_experts)

    tk_layer_sums = tk_3d.sum(axis=2)
    mp_layer_sums = mp_3d.sum(axis=2)

    assert topk_freq_arr.min() >= 0.0, f"topk_freq has negative values: {topk_freq_arr.min()}"
    assert mean_probs_arr.min() >= 0.0, f"mean_probs has negative values: {mean_probs_arr.min()}"
    assert np.allclose(tk_layer_sums, routed_top_k, atol=1e-3), (
        f"topk_freq layer sums not close to {routed_top_k}: "
        f"range [{tk_layer_sums.min():.4f}, {tk_layer_sums.max():.4f}]"
    )
    assert np.allclose(mp_layer_sums, 1.0, atol=1e-3), (
        f"mean_probs layer sums not close to 1.0: "
        f"range [{mp_layer_sums.min():.4f}, {mp_layer_sums.max():.4f}]"
    )
    logger.info(
        f"  topk_freq:  range=[{topk_freq_arr.min():.4f}, {topk_freq_arr.max():.4f}], "
        f"layer-sum range=[{tk_layer_sums.min():.4f}, {tk_layer_sums.max():.4f}]"
    )
    logger.info(
        f"  mean_probs: range=[{mean_probs_arr.min():.6f}, {mean_probs_arr.max():.4f}], "
        f"layer-sum range=[{mp_layer_sums.min():.4f}, {mp_layer_sums.max():.4f}]"
    )

    # ── Step 6: save ─────────────────────────────────────────────────────────
    tk_path = os.path.join(args.output_dir, "embeddings_doc_topk_freq.npy")
    mp_path = os.path.join(args.output_dir, "embeddings_doc_probs.npy")
    np.save(tk_path, topk_freq_arr)
    np.save(mp_path, mean_probs_arr)
    logger.info(f"\nSaved {tk_path}  shape={topk_freq_arr.shape}")
    logger.info(f"Saved {mp_path}  shape={mean_probs_arr.shape}")

    meta_path = os.path.join(args.output_dir, "metadata_docs.jsonl.gz")
    with gzip.open(meta_path, "wt") as f:
        for i, (doc, label) in enumerate(zip(all_docs, all_labels)):
            preview = tokenizer.decode(doc[:80].tolist(), skip_special_tokens=True)[:200]
            f.write(
                json.dumps(
                    {
                        "doc_index": i,
                        "source": label,
                        "doc_len": int(len(doc)),
                        "preview": preview,
                    }
                )
                + "\n"
            )
    logger.info(f"Saved {meta_path}")

    info_out = {
        "model_path": args.model_path,
        "num_layers": num_layers,
        "num_standard_experts": num_standard_experts,
        "num_shared_experts": moe_cfg["num_shared_experts"],
        "top_k": moe_cfg["top_k"],
        "routed_top_k": routed_top_k,
        "num_topics": num_topics,
        "target_tokens": args.target_tokens,
        "tokens_per_topic": tokens_per_topic,
        "total_docs": num_docs,
        "total_tokens": int(total_tokens),
        "shuffle_seed": args.shuffle_seed,
        "topics": sorted(sources.keys()),
        "composition_file": args.composition_file,
    }
    info_path = os.path.join(args.output_dir, "info.json")
    with open(info_path, "w") as f:
        json.dump(info_out, f, indent=2)
    logger.info(f"Saved {info_path}")
    logger.info("\nDone.")


if __name__ == "__main__":
    main()
