(() => {
  const d=window.ICSL_REPORT_DATA||{runs:[]};
  title.textContent=d.title; setup.textContent=d.setup; updated.textContent=`Updated ${d.updated}`; selection.textContent=d.selection;
  const colors=['#2563eb','#7c3aed','#dc5a39','#0f9d76','#e09200','#ca3f64','#1874a8','#7f6752'];
  const key=r=>r.series||r.scheduler||`WD ${r.wd}`; const series=[...new Set(d.runs.map(key))];
  series.forEach((s,i)=>legend.insertAdjacentHTML('beforeend',`<label><span class="dot" style="background:${colors[i%colors.length]}"></span>${s}</label>`));
  const metrics=[['train','Train CE'],['validation','DCLM validation CE'],['acc','HellaSwag accuracy'],['bpb','HellaSwag BPB'],['avg8','8-task average (no BoolQ)'],['stable3','Stable 3-task average'],['arc_easy','ARC-Easy'],['arc_challenge','ARC-Challenge'],['csqa','CSQA'],['openbookqa','OpenBookQA'],['piqa','PIQA'],['socialiqa','SocialIQA'],['winogrande','Winogrande']];
  const value=(r,k)=>{if(k==='validation')return r.validation??r.c4;if(k==='avg8'){const q=['arc_challenge','arc_easy','csqa','acc','openbookqa','piqa','socialiqa','winogrande'].map(x=>x==='acc'?r.acc:r.downstream?.[x]).filter(Number.isFinite);return q.length===8?q.reduce((a,b)=>a+b,0)/8:null}if(k==='stable3'){const q=[r.downstream?.arc_easy,r.acc,r.downstream?.piqa].filter(Number.isFinite);return q.length===3?q.reduce((a,b)=>a+b,0)/3:null}return r[k]??r.downstream?.[k]};
  metrics.forEach(([m,label])=>{const pts=d.runs.map((r,i)=>({r,i,v:value(r,m)})).filter(x=>Number.isFinite(x.v));const card=document.createElement('div');card.className='card chart';card.innerHTML=`<h3>${label}</h3>`;const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');card.append(svg);charts.append(card);if(!pts.length){svg.innerHTML='<text x="18" y="36">Pending results</text>';return}const lo=Math.min(...pts.map(x=>x.v)),hi=Math.max(...pts.map(x=>x.v)),pad=Math.max((hi-lo)*.18,.01),y=v=>205-(v-(lo-pad))/(hi-lo+2*pad)*165,x=e=>35+(e-1)*48;svg.innerHTML=`<line x1="30" y1="205" x2="275" y2="205" stroke="#aeb7c7"/><text x="2" y="205">${(lo-pad).toFixed(3)}</text><text x="2" y="40">${(hi+pad).toFixed(3)}</text>`;series.forEach((s,si)=>{const p=pts.filter(z=>key(z.r)===s).sort((a,b)=>a.r.epoch-b.r.epoch);if(p.length>1)svg.insertAdjacentHTML('beforeend',`<polyline fill="none" stroke="${colors[si%colors.length]}" stroke-width="2" points="${p.map(z=>`${x(z.r.epoch)},${y(z.v)}`).join(' ')}"/>`);p.forEach(z=>svg.insertAdjacentHTML('beforeend',`<circle cx="${x(z.r.epoch)}" cy="${y(z.v)}" r="4" fill="${colors[si%colors.length]}"/><text class="value" x="${x(z.r.epoch)+5}" y="${y(z.v)-6}">${z.v.toFixed(m==='acc'||m==='avg8'||m==='stable3'||m.includes('arc')||['csqa','openbookqa','piqa','socialiqa','winogrande'].includes(m)?2:3)}</text><text x="${x(z.r.epoch)-3}" y="222">E${z.r.epoch}</text>`))})});
  d.runs.filter(r=>!['failed','canceled'].includes(r.status)&&r.kind!=='evaluation').forEach(r=>rows.insertAdjacentHTML('beforeend',`<tr><td>${key(r)}</td><td>${r.epoch}</td><td>${r.lr||'—'}</td><td>${r.wd||'—'}</td><td>${r.status}</td><td>${r.train??'—'}</td><td>${r.validation??r.c4??'—'}</td><td>${r.acc??'—'}</td><td>${r.bpb??'—'}</td><td>${r.wandb?`<a href="https://wandb.ai/ai2-llm/sewonm-icsl/runs/${r.wandb}">${r.wandb}</a>`:'—'}</td><td>${r.beaker?`<a href="https://beaker.org/ex/${r.beaker}">experiment</a>`:'—'}</td></tr>`));
})();
